import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '..');
const distDir = path.join(projectRoot, 'dist');

const entries = [
  {
    input: path.join(projectRoot, 'src', 'platform', 'turbowarp', 'index.js'),
    output: path.join(distDir, 'turbowarp-unsandboxed.js'),
    banner: 'TurboWarp unsandboxed build'
  },
  {
    input: path.join(projectRoot, 'src', 'platform', 'gandi', 'remote.js'),
    output: path.join(distDir, 'gandi-normal-remote.js'),
    banner: 'Gandi normal remote build'
  },
  {
    input: path.join(projectRoot, 'src', 'platform', 'gandi', 'index.js'),
    output: path.join(distDir, 'gandi-approved.js'),
    banner: 'Gandi approved build'
  }
];

function resolveImport(fromFile, specifier) {
  if (!specifier.startsWith('.')) {
    throw new Error(`Only relative imports are supported: ${specifier} in ${fromFile}`);
  }

  return path.resolve(path.dirname(fromFile), specifier);
}

function parseImportBindings(bindingSource) {
  return bindingSource
    .split(',')
    .map((part) => part.trim())
    .filter(Boolean)
    .map((part) => {
      const match = /^([A-Za-z_$][\w$]*)\s+as\s+([A-Za-z_$][\w$]*)$/.exec(part);
      if (!match) {
        return part;
      }

      return `${match[1]}: ${match[2]}`;
    })
    .join(', ');
}

function transformModule(filePath, addModule) {
  const rawCode = fs.readFileSync(filePath, 'utf8');
  let code = rawCode;
  const exportedNames = [];
  const explicitExports = [];

  code = code.replace(
    /^\s*import\s+\{([^}]+)\}\s+from\s+['"](.+?)['"];\s*$/gm,
    (_match, bindings, specifier) => {
      const dependencyId = addModule(resolveImport(filePath, specifier));
      return `const { ${parseImportBindings(bindings)} } = __require(${dependencyId});`;
    }
  );

  code = code.replace(/^\s*export\s+class\s+([A-Za-z_$][\w$]*)/gm, (_match, name) => {
    exportedNames.push(name);
    return `class ${name}`;
  });

  code = code.replace(/^\s*export\s+function\s+([A-Za-z_$][\w$]*)/gm, (_match, name) => {
    exportedNames.push(name);
    return `function ${name}`;
  });

  code = code.replace(/^\s*export\s+(const|let|var)\s+([A-Za-z_$][\w$]*)/gm, (_match, keyword, name) => {
    exportedNames.push(name);
    return `${keyword} ${name}`;
  });

  code = code.replace(/^\s*export\s*\{\s*([^}]+)\s*\};?\s*$/gm, (_match, names) => {
    for (const part of names.split(',')) {
      const trimmed = part.trim();
      if (!trimmed) {
        continue;
      }

      const aliasMatch = /^([A-Za-z_$][\w$]*)\s+as\s+([A-Za-z_$][\w$]*)$/.exec(trimmed);
      if (aliasMatch) {
        explicitExports.push(`__exports.${aliasMatch[2]} = ${aliasMatch[1]};`);
        continue;
      }

      explicitExports.push(`__exports.${trimmed} = ${trimmed};`);
    }

    return '';
  });

  const exportFooter = [
    ...new Set(exportedNames).values().map((name) => `__exports.${name} = ${name};`),
    ...explicitExports
  ].join('\n');

  return `function(__require, __exports) {\n${code}\n${exportFooter}\n}`;
}

function bundleEntry(entryFile, banner) {
  const moduleIds = new Map();
  const modules = [];

  function addModule(filePath) {
    const resolvedPath = path.resolve(filePath);
    if (moduleIds.has(resolvedPath)) {
      return moduleIds.get(resolvedPath);
    }

    const id = modules.length;
    moduleIds.set(resolvedPath, id);
    modules.push({
      id,
      code: null
    });

    modules[id].code = transformModule(resolvedPath, addModule);
    return id;
  }

  const entryId = addModule(entryFile);

  const serializedModules = modules
    .map((module) => `  ${module.id}: ${module.code}`)
    .join(',\n');

  return `/* ${banner} | generated by scripts/build.mjs */\n(function() {\nconst __modules = {\n${serializedModules}\n};\nconst __cache = {};\nfunction __require(id) {\n  if (__cache[id]) {\n    return __cache[id];\n  }\n\n  const __exports = {};\n  __cache[id] = __exports;\n  __modules[id](__require, __exports);\n  return __exports;\n}\n\n__require(${entryId});\n})();\n`;
}

export function buildAll() {
  fs.rmSync(distDir, { recursive: true, force: true });
  fs.mkdirSync(distDir, { recursive: true });

  for (const entry of entries) {
    const output = bundleEntry(entry.input, entry.banner);
    fs.writeFileSync(entry.output, output, 'utf8');
    console.log(`Built ${path.relative(projectRoot, entry.output)}`);
  }
}

if (process.argv[1] === __filename) {
  buildAll();
}
